#!/bin/bash
# Simple template builder
# Copyrigt 2016 by luk3yx.
# All rights reserved.
DIR=$(pwd)
in="$1"
template="./template.html"
out="$2"
alldir="./html"
alldir=$(readlink -m "$alldir")

function ask {
echo "y/N"
read -n1 reply
if [ "$reply" != "y" ] && [ "$reply" != "Y" ]; then
    return 1
fi
}
if [ "$#" = "0" ] && echo "All files/folders?" && ask; then
    cd "$alldir"
    files=(*)
    cd "$DIR"
    echo y | exec "$0" "${files[@]}"
    exit
fi
echo "Multiple?"
if [ "$Multiple" != "false" ] && ask; then
    export Multiple="false"
    export ASSUMEvars="true"
    export noprompt="true"
    for i in "$@"; do
        bash "$0" "$i"
    done
    exit
fi
echo "Assume variables?"
if [ "$ASSUMEvars" = "true" ] || ask; then
    out="../$in"
    in="./html/$in"
fi

in=$(readlink -m "$in")
template=$(readlink -m "$template")
out=$(readlink -m "$out")

echo "$in"
echo "$template"
echo "$out"

[ "$noprompt" = true ] || ask || exit

indent="        "
string="$indent<h1>Don't edit me. I help the auto-generator.</h1>"

function hit {
while IFS='' read -r line; do
    echo "$indent$line" >> "$out"
done < "$in"
}

rm "$out"
year=$(date +%Y)
date="This page created on: "$(date -u)'<br/>'
while IFS='' read -r line; do
    if [ "$line" = "$string" ]; then
        hit
    else
        pline="${line//<!--YEAR -->/$year }"
        pline="${pline//<!--DATE-->/$date}"
        echo "$pline" >> "$out"
    fi
done < "$template"
