#!/bin/bash
# Simple template builder
# Copyrigt 2016 by luk3yx.
# All rights reserved.
DIR=$(pwd)
template="./template.html"
stemplate="./template.slim"
echo "Making SLIM template..."
rm "$stemplate"
while IFS='' read -r line; do
    case "$line" in
        *"<h1>Don't edit me. I help the auto-generator.</h1>"*)
        echo "Found content line"
        cline='== content'
        ;;
        *)
        cline="| $line"
        ;;
    esac
    echo "$cline" >> "$stemplate"
done <"$template"
echo "Building HTML files..."
echo y | ./build-individual
echo "Done! Press any key to exit."
read -sn1 nothing
